//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3_BYME
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Books()
        {
            this.ChiTietBooks = new HashSet<ChiTietBooks>();
        }
    
        public string IdBook { get; set; }
        public string IdKhachHang { get; set; }
        public string IdNhanVien { get; set; }
        public Nullable<int> TienCoc { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual KhachHangs KhachHangs { get; set; }
        public virtual NhanViens NhanViens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietBooks> ChiTietBooks { get; set; }
    }
}
