//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3_BYME
{
    using System;
    using System.Collections.Generic;
    
    public  class ChiTietSuDungDichVu
    {
        public int ID_ChiTietSuDungDichVu { get; set; }
        public string ID_Phong { get; set; }
        public string ID_DichVu { get; set; }
        public string ID_HoaDon { get; set; }
        public Nullable<System.DateTime> NgaySuDung { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual DichVu DichVu { get; set; }
        public virtual HoaDon HoaDon { get; set; }
        public virtual PHONG PHONG { get; set; }
    }
}
