//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3_BYME
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietBook
    {
        public string IdChiTietBook { get; set; }
        public string IdPhong { get; set; }
        public string IdBook { get; set; }
        public Nullable<System.DateTime> NgayCheckInPhong { get; set; }
        public Nullable<System.DateTime> NgayCheckOutPhong { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual PHONG PHONG { get; set; }
    }
}
