//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3_BYME
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDons
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDons()
        {
            this.ChiTietSuDungDichVus = new HashSet<ChiTietSuDungDichVus>();
            this.ChiTietThuePhongs = new HashSet<ChiTietThuePhongs>();
        }
    
        public string IdHoaDon { get; set; }
        public string IdKhachHang { get; set; }
        public string IdNhanVien { get; set; }
        public Nullable<System.DateTime> NgayHoaDon { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
        public string GhiChu { get; set; }
        public Nullable<decimal> TienTraTruoc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietSuDungDichVus> ChiTietSuDungDichVus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietThuePhongs> ChiTietThuePhongs { get; set; }
        public virtual KhachHangs KhachHangs { get; set; }
        public virtual LamHus LamHus { get; set; }
        public virtual NhanViens NhanViens { get; set; }
    }
}
