//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3_BYME
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDon()
        {
            this.ChiTietSuDungDichVus = new HashSet<ChiTietSuDungDichVu>();
            this.ChiTietThuePhongs = new HashSet<ChiTietThuePhong>();
        }
    
        public string IdHoaDon { get; set; }
        public string IdKhachHang { get; set; }
        public string IdNhanVien { get; set; }
        public Nullable<System.DateTime> NgayHoaDon { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
        public string GhiChu { get; set; }
        public Nullable<decimal> TienTraTruoc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietSuDungDichVu> ChiTietSuDungDichVus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietThuePhong> ChiTietThuePhongs { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual LamHu LamHu { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
