//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3_BYME
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phongs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phongs()
        {
            this.ChiTietBooks = new HashSet<ChiTietBooks>();
            this.ChiTietSuDungDichVus = new HashSet<ChiTietSuDungDichVus>();
            this.ChiTietThuePhongs = new HashSet<ChiTietThuePhongs>();
            this.LamHus = new HashSet<LamHus>();
            this.VatDungPhongs = new HashSet<VatDungPhongs>();
        }
    
        public string IdPhong { get; set; }
        public string IdLoaiPhong { get; set; }
        public string TenPhong { get; set; }
        public Nullable<int> DonGiaPhong { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietBooks> ChiTietBooks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietSuDungDichVus> ChiTietSuDungDichVus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietThuePhongs> ChiTietThuePhongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LamHus> LamHus { get; set; }
        public virtual LoaiPhongs LoaiPhongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VatDungPhongs> VatDungPhongs { get; set; }
    }
}
