//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3_BYME
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLKS_DB : DbContext
    {
        public QLKS_DB()
            : base("name=QLKS_DB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<ChiTietBooks> ChiTietBooks { get; set; }
        public virtual DbSet<ChiTietSuDungDichVus> ChiTietSuDungDichVus { get; set; }
        public virtual DbSet<ChiTietThuePhongs> ChiTietThuePhongs { get; set; }
        public virtual DbSet<ChucVus> ChucVus { get; set; }
        public virtual DbSet<DichVus> DichVus { get; set; }
        public virtual DbSet<HoaDons> HoaDons { get; set; }
        public virtual DbSet<KhachHangs> KhachHangs { get; set; }
        public virtual DbSet<LamHus> LamHus { get; set; }
        public virtual DbSet<LichSuDangNhaps> LichSuDangNhaps { get; set; }
        public virtual DbSet<LoaiPhongs> LoaiPhongs { get; set; }
        public virtual DbSet<LoaiVatDungs> LoaiVatDungs { get; set; }
        public virtual DbSet<NhanViens> NhanViens { get; set; }
        public virtual DbSet<Phongs> Phongs { get; set; }
        public virtual DbSet<TaiKhoans> TaiKhoans { get; set; }
        public virtual DbSet<VatDungPhongs> VatDungPhongs { get; set; }
    }
}
